contacts_manager/workshop_ind/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from contacts.views import add_new_person_view, modify_person_view, modify_address_view, delete_address_view, \
    add_address_view, add_phone_view, modify_phone_view, delete_phone_view, add_email_view, modify_email_view, \
    delete_email_view, delete_person_view, show_all_users_view, show_user_details_view, add_group_view, \
    add_to_group_view, show_all_groups_view, group_search_view, delete_group_view, delete_person_from_group_view, \
    modify_group_view

urlpatterns = [

    path('admin/', admin.site.urls),
    path('new', add_new_person_view),
    path('', show_all_users_view),
    path('group_search', group_search_view),

    re_path(r'^modify/(?P<id>[0-9]+)$', modify_person_view),
    re_path(r'^delete_person/(?P<id>[0-9]+)$', delete_person_view),
    re_path(r'^show_person_details/(?P<id>[0-9]+)$', show_user_details_view),

    re_path(r'^modify_address/(?P<id>[0-9]+)$', modify_address_view),
    re_path(r'^delete/(?P<id>[0-9]+)$', delete_address_view),
    re_path(r'^add_address/(?P<id>[0-9]+)$', add_address_view),

    re_path(r'^add_phone/(?P<id>[0-9]+)$', add_phone_view),
    re_path(r'^modify_phone/(?P<id>[0-9]+)$', modify_phone_view),
    re_path(r'^delete_phone/(?P<id>[0-9]+)$', delete_phone_view),

    re_path(r'^add_email/(?P<id>[0-9]+)$', add_email_view),
    re_path(r'^modify_email/(?P<id>[0-9]+)$', modify_email_view),
    re_path(r'^delete_email/(?P<id>[0-9]+)$', delete_email_view),

    path('add_group', add_group_view),
    re_path(r'^add_to_group/(?P<id>[0-9]+)$', add_to_group_view),
    path('show_all_groups', show_all_groups_view),
    re_path(r'^delete_group/(?P<id>[0-9]+)$', delete_group_view),
    re_path(r'^delete_user_from_group/(?P<id>[0-9]+)/(?P<person_id>[0-9]+)$', delete_person_from_group_view),
    re_path(r'^modify_group/(?P<id>[0-9]+)$', modify_group_view),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts_manager/contacts/models.py
from django.db import models


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    description = models.TextField()
    picture = models.ImageField(null=True)
    address = models.ForeignKey('Address', on_delete=models.SET_NULL, null=True)


class Address(models.Model):
    city = models.CharField(max_length=64)
    street_name = models.CharField(max_length=64)
    house_number = models.CharField(max_length=6)
    flat_number = models.CharField(max_length=6, null=True)


class Phone(models.Model):
    phone_number = models.BigIntegerField()
    PHONE_TYPES = (
        (1, "work"),
        (2, "home"),
        (3, "private")
    )
    phone_type = models.IntegerField(choices=PHONE_TYPES)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Email(models.Model):
    email = models.CharField(max_length=64)
    EMAIL_TYPES = (
        (1, "work"),
        (2, "home"),
        (3, "private")
    )
    email_type = models.IntegerField(choices=EMAIL_TYPES)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)


class Groups(models.Model):
    name = models.CharField(max_length=64)
    person = models.ManyToManyField(Person)

contacts_manager/contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from contacts.models import Person, Address, Phone, Email, Groups
from django.conf import settings
from os import path, rename, remove

# this is image processing library
from PIL import Image

# Create your views here.

def add_new_person_view(request):
    if request.method == "POST":
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        description = request.POST.get('description')
        next = request.POST.get('next')
        if 'picture' in request.FILES:
            picture = request.FILES['picture']
            new_guy = Person.objects.create(name=name, surname=surname, description=description, picture=picture)

            # avatar will be 400px x 400px so we define min and max dimensions in px
            max_picture_width = 600
            min_picture_width = 400
            min_picture_height = 400
            max_picture_height = 600

            # check if this is an image and check required dimensions and file format
            full_path_to_file = settings.MEDIA_ROOT + str(new_guy.picture)

            # not all formats are fully supported by Pillow
            # perhaps there is more but no time to test it

            non_convertable_image_files = [".png", ".gif", ".nef", ".cr2", ".psd"]

            try:
                im = Image.open(full_path_to_file)
                picture_width = im.size[0]
                picture_height = im.size[1]
                if picture_width < min_picture_width or picture_height < min_picture_height:
                    e = "Picture should be at least 400px at width and height!"
                    im.close()
                    remove(full_path_to_file)
                    new_guy.delete()
                    return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})
                filename, extension = path.splitext((str(new_guy.picture)).lower())
                if extension in non_convertable_image_files:
                    raise Exception
            except Exception as e:
                e = "This is not a supported image file. Allowed formats: jpg, tif, bmp."
                remove(full_path_to_file)
                new_guy.delete()
                return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})

            # resize image, convert file to jpg
            ratio = picture_width / picture_height

            if picture_width > max_picture_width or picture_height > max_picture_height:
                if ratio > 1:
                    picture_height = min_picture_height
                    picture_width = picture_height * ratio
                else:
                    picture_width = min_picture_width
                    picture_height = picture_width / ratio

            picture_height = int(round(picture_height, 0))
            picture_width = int(round(picture_width, 0))

            filename, extension = path.splitext((str(new_guy.picture).lower()))
            im = im.resize((picture_width, picture_height))
            outfile = filename + ".jpg"

            if new_guy.picture != outfile:
                try:
                    im.save(settings.MEDIA_ROOT + outfile, "JPEG")
                    new_guy.picture = outfile
                    new_guy.save()
                except IOError as e:
                    print("This file can not be converted to jpg.")
                except Exception as e:
                    im.close()
                    return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})
            else:
                im.save(settings.MEDIA_ROOT + outfile, "JPEG")
                new_guy.picture = outfile
                new_guy.save()

            im.close()

            # rename picture if name and surname were given
            if new_guy.name and new_guy.surname:
                filename, extension = path.splitext(str(new_guy.picture))
                new_picture_name = "avatar-" + new_guy.name + "-" + new_guy.surname + extension
                rename(settings.MEDIA_ROOT + str(new_guy.picture), settings.MEDIA_ROOT + new_picture_name)
                new_guy.picture = new_picture_name
                new_guy.save()
        else:
            new_guy = Person.objects.create(name=name, surname=surname, description=description)

        msg = "New person added!"
        ctx = {"msg": msg,
               "new_guy": new_guy,
               }
        return render(request, "add_new_person.html", ctx)

    elif request.method == "GET":
        return render(request, "add_new_person.html", {})


def modify_person_view(request, id):
    if request.method == "POST":

        modified_person = Person.objects.get(pk=id)
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        description = request.POST.get('description')
        next = request.POST.get('next')

        if 'picture' in request.FILES:
            picture = request.FILES['picture']
            modified_person.name = name
            modified_person.surname = surname
            modified_person.description = description

            # avatar will be 400px x 400px so we define min and max dimensions in px
            max_picture_width = 600
            min_picture_width = 400
            min_picture_height = 400
            max_picture_height = 600

            non_convertable_image_files = [".png", ".gif", ".nef", ".cr2", ".psd"]

            try:
                im = Image.open(picture)
                picture_width = im.size[0]
                picture_height = im.size[1]
                if picture_width < min_picture_width or picture_height < min_picture_height:
                    e = "Picture should be at least 400px at width and height!"
                    im.close()
                    return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})
                filename, extension = path.splitext((str(picture)).lower())
                if extension in non_convertable_image_files:
                    raise Exception
            except Exception as e:
                e = "This is not a supported image file. Allowed formats: jpg, tif, bmp."
                return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})

            # resize image, convert file to jpg
            ratio = picture_width / picture_height

            if picture_width > max_picture_width or picture_height > max_picture_height:
                if ratio > 1:
                    picture_height = min_picture_height
                    picture_width = picture_height * ratio
                else:
                    picture_width = min_picture_width
                    picture_height = picture_width / ratio

            picture_height = int(round(picture_height, 0))
            picture_width = int(round(picture_width, 0))

            filename, extension = path.splitext((str(picture).lower()))
            im = im.resize((picture_width, picture_height))
            outfile = filename + ".jpg"

            if modified_person.picture != outfile:
                try:
                    im.save(settings.MEDIA_ROOT + outfile, "JPEG")
                    modified_person.picture = outfile
                    modified_person.save()
                except IOError as e:
                    print("This file can not be converted to jpg.")
                except Exception as e:
                    im.close()
                    return render(request, "standard_error_message.html", {"error_msg": e, 'next': next})
            else:
                im.save(settings.MEDIA_ROOT + outfile, "JPEG")
                modified_person.picture = outfile
                modified_person.save()

            im.close()

            # rename picture if name and surname were given
            if modified_person.name and modified_person.surname:
                filename, extension = path.splitext(str(modified_person.picture))
                new_picture_name = "avatar-" + modified_person.name + "-" + modified_person.surname + extension
                rename(settings.MEDIA_ROOT + str(modified_person.picture), settings.MEDIA_ROOT + new_picture_name)
                modified_person.picture = new_picture_name
                modified_person.save()
        else:
            modified_person.name = name
            modified_person.surname = surname
            modified_person.description = description
            modified_person.save()

        msg = "Personal details modified!"

        ctx = {"msg": msg, "modified_person": modified_person, 'next': next, }

        return render(request, "modify_person_response.html", ctx, )

    elif request.method == "GET":

        id = int(id)

        modified_person = Person.objects.get(pk=id)
        address_id = modified_person.address_id

        if address_id is None:
            address = None
            phone_number = Phone.objects.filter(person_id=id)
            phone_types = Phone.PHONE_TYPES

            emails = Email.objects.filter(person_id=id)
            email_types = Email.EMAIL_TYPES

            ctx = {
                "modified_person": modified_person,
                "address": address,
                "phone_number": phone_number,
                "phone_types": phone_types,
                "emails": emails,
                "email_types": email_types,

            }

            return render(request, "modify_person.html", ctx, )

        address = Address.objects.get(pk=address_id)

        phone_number = Phone.objects.filter(person_id=id)
        phone_types = Phone.PHONE_TYPES

        emails = Email.objects.filter(person_id=id)
        email_types = Email.EMAIL_TYPES

        ctx = {
            "modified_person": modified_person,
            "address": address,
            "phone_number": phone_number,
            "phone_types": phone_types,
            "emails": emails,

contacts_manager/contacts/templates/add_address_response.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3">{{ msg }}</h3>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">First Name</th>
                <th scope="col" class="centerTableCol">Last Name</th>
                <th scope="col" class="centerTableCol">Street</th>
                <th scope="col" class="centerTableCol">House Number</th>
                <th scope="col" class="centerTableCol">Flat Number</th>
                <th scope="col" class="centerTableCol">City</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="centerTableCol">{{ modified_person.name }}</td>
                <td class="centerTableCol">{{ modified_person.surname }}</td>
                <td class="centerTableCol">{{ address.street_name }}</td>
                <td class="centerTableCol">{{ address.house_number }}</td>
                <td class="centerTableCol">{{ address.flat_number }}</td>
                <td class="centerTableCol">{{ address.city }}</td>
            </tr>
            </tbody>
        </table>
        <hr>
    <a href="{{ next }}">
        <button class="btn btn-primary">Back</button>
    </a>
{% else %}
Nothing here .......!!!! Check code!

{% endif %}

{% include "footer.html" %}

contacts_manager/contacts/templates/add_email_response.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3">{{ msg }}</h3>
    <table class="table">
    <thead class="thead-light">
    <tr>
        <th scope="col" class="centerTableCol">Email</th>
        <th scope="col" class="centerTableCol">Type</th>
    </tr>
    </thead>
    <tbody>
    <tr>
    <td class="centerTableCol">{{ emails.email }}</td>
    <td class="centerTableCol">{{ emails.get_email_type_display}}</td>
        </tr>
        </tbody>
        </table>
        <hr>
    <a href="{{ next }}">
        <button class="btn btn-primary">Back</button>
    </a>
        {% else %}
    Nothing here .......!!!! Check code!

{% endif %}

{% include "footer.html" %}

contacts_manager/contacts/templates/add_group.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3">{{ msg }}</h3>

    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col" class="centerTableCol">Group Name</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="centerTableCol">{{ group.name }}</td>
        </tr>
        </tbody>
    </table>

{% else %}

    <h3 class="h3 h3Colors">Add new Group:</h3>

    <form action="/add_group" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Group Name</label>
            <input type="text" name="name" maxlength="64" class="form-control">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Add Group</button>
    </form>
{% endif %}

{% include "footer.html" %}

contacts_manager/contacts/templates/add_phone_response.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3">{{ msg }}</h3>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Telephone Number</th>
                <th scope="col" class="centerTableCol">Type</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="centerTableCol">{{ new_phone.phone_number }}</td>
                <td class="centerTableCol">{{ new_phone.get_phone_type_display }}</td>
            </tr>
            </tbody>
        </table>
        <hr>
    <a href="{{ next }}">
        <button class="btn btn-primary">Back</button>
    </a>
{% else %}
Nothing here .......!!!! Check code!

{% endif %}

{% include "footer.html" %}

contacts_manager/contacts/templates/add_to_group.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3 h3Colors">User: {{ user.name }} {{ user.surname }} {{ msg }}</h3>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col" class="centerTableCol">Group Name</th>
        </tr>
        </thead>
        <tbody>
        {% for gr in user_groups %}
        <tr>
            <td class="centerTableCol">{{ gr.name }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


{% else %}

    <h3 class="h3 h3Colors">{{ user.name }} {{ user.surname }} - Groups Assigment:</h3>
    <form action="/add_to_group/{{ user.id }}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Select Groups You want to be member of:</label>
            <select multiple class="form-control" name="groups" id="groupsSelection">
                {% for gr in groups %}
                    {% if gr in user_groups %}
                        <option selected value="{{ gr.id }}">{{ gr.name }}</option>
                        {% else %}
                            <option value="{{ gr.id }}">{{ gr.name }}</option>
                        {% endif %}
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Assign to Groups</button>
    </form>
{% endif %}
{% include "footer.html" %}

contacts_manager/contacts/templates/footer.html
<!-- footer start -->
</div>
</body>
</html>

contacts_manager/contacts/templates/group_search.html
{% include  "header.html" %}
{% if msg %}
    <h3 class="h3 h3Colors">{{ msg }}</h3>
    {% if user %}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Surname</th>
                <th scope="col" class="centerTableCol">Name</th>
                <th scope="col" class="centerTableCol">City</th>
                <th scope="col" class="centerTableCol">Groups</th>
                <th scope="col" class="centerTableCol">Group Assigment</th>
                <th scope="col" class="centerTableCol">Modify</th>
                <th scope="col" class="centerTableCol">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for user in user %}
                <tr>
                    <td><a href="/show_person_details/{{ user.id }}">{{ user.surname }}</a></td>
                    <td><a href="/show_person_details/{{ user.id }}">{{ user.name }}</a></td>
                    <td>{{ user.address.city }}</td>
                    <td>
                        {% if user.groups_set.all %}
                            {% for gr in user.groups_set.all %}
                                {{ gr.name }} <br>
                            {% endfor %}
                        {% else %}
                            Not assigned to any groups
                        {% endif %}
                    </td>
                    <td class="centerTableCol">
                        <a href="/add_to_group/{{ user.id }}">
                            <button class="btn btn-primary">Group Assign</button>
                    </td>
                    <td class="centerTableCol">
                        <a href="/modify/{{ user.id }}">
                            <button class="btn btn-warning">Modify</button>
                    </td>
                    <td class="centerTableCol">
                        <a href="/delete_person/{{ user.id }}">
                            <button class="btn btn-danger">Delete!</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4 class="h4">Search didnt return any results.</h4>
    {% endif %}


{% else %}
    <h3 class="h3 h3Colors">User Search</h3>

    <form action="/group_search" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Name</label>
            <input type="text" name="name" maxlength="64" class="form-control shortFormsFields">
        </div>
        <div class="form-group">
            <label>Surname</label>
            <input type="text" name="surname" maxlength="64" class="form-control shortFormsFields">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

{% endif %}
{% include "footer.html" %}

contacts_manager/contacts/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {#link to fonts awesome#}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">
    {#link to Bootstrap files#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>

    <script src="{% static 'js/scripts.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <title>Ksiazka Adresowa</title>
</head>
<body>
<div class="websiteHeader">
    <nav class="navbar navbar-expand-lg navbar-dark headerRooms">
        <a class="navbar-brand" id="logo">bookAddress</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="/">Home</a>
                <a class="nav-item nav-link" href="/new">Add User</a>
                <a class="nav-item nav-link" href="/">Browse Users</a>
                <a class="nav-item nav-link" href="/add_group">Add Group</a>
                <a class="nav-item nav-link" href="/show_all_groups">All Groups</a>
                <a class="nav-item nav-link" href="/group_search">Search</a>
            </div>
        </div>
    </nav>

</div>
<div class="mainContainer">
    <!-- end of header -->

contacts_manager/contacts/templates/modify_address_response.html
{% include  "header.html" %}

{% if msg %}
    <h3 class="h3">{{ msg }}</h3>
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">First Name</th>
                <th scope="col" class="centerTableCol">Last Name</th>
                <th scope="col" class="centerTableCol">Street</th>
                <th scope="col" class="centerTableCol">House Number</th>
                <th scope="col" class="centerTableCol">Flat Number</th>
                <th scope="col" class="centerTableCol">City</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td class="centerTableCol">{{ modified_person.name }}</td>
                <td class="centerTableCol">{{ modified_person.surname }}</td>
                <td class="centerTableCol">{{ address.street_name }}</td>
                <td class="centerTableCol">{{ address.house_number }}</td>
                <td class="centerTableCol">{{ address.flat_number }}</td>
                <td class="centerTableCol">{{ address.city }}</td>
            </tr>
            </tbody>
        </table>
        <hr>
    <a href="{{ next }}">
        <button class="btn btn-primary">Back</button>
    </a>
{% else %}
Nothing here .......!!!! Check code!

{% endif %}

{% include "footer.html" %}

contacts_manager/contacts/templates/show_all_groups.html
{% include  "header.html" %}

{% if msg %}
    <h4 style="h4">{{ msg }}</h4>

{% else %}
    <h3 class="h3 h3Colors">All Groups</h3>
    {% for gr in groups %}
        <h4 class="h4 h4Colors" style="height: 60px">
            <p class="pGroupsHeader">Group: {{ gr.name }}</p>
                       <a href="/delete_group/{{ gr.id }}" style="float: right">
                <button class="btn btn-danger">Delete Group!</button>
            </a>
            <a href="/modify_group/{{ gr.id }}" style="float: right">
                <button class="btn btn-warning" style="margin: 0 10px">Modify Group</button><p></p>
            </a>

        </h4>
        {% if gr.person.all %}
            <table class="table">
                <tbody>
                <thead class="thead-light">
                <th scope="col">User</th>
                <th scope="col" style="text-align: right">Remove User from Group</th>
                </thead>

                {% for usr in gr.person.all %}
                    <tr>
                        <td>
                            <a href="/show_person_details/{{ usr.id }}">{{ usr.name }} {{ usr.surname }}</a></td>
                        <td class="tdAlignRight"><a href="/delete_user_from_group/{{ gr.id }}/{{ usr.id }}">
                            <button class="btn btn-danger">Remove</button>
                        </a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No users in this Group</p>
        {% endif %}
    {% endfor %}

{% endif %}
{% include "footer.html" %}

contacts_manager/contacts/templates/show_user_details.html
{% include  "header.html" %}
{% if msg %}

{% else %}
    <h3 class="h3 h3Colors">User: {{ person.name }} {{ person.surname }}</h3>
    <h4 class="h4 h4Colors">Basic information:</h4>
    <div class="userDetailsDiv">
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Label</th>
                <th scope="col" class="centerTableCol">Basic Data</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Name</td>
                <td>{{ person.name }}</td>
            </tr>
            <tr>
                <td>Surname</td>
                <td>{{ person.surname }}</td>
            </tr>
            <tr>
                <td>Description</td>
                <td>{{ person.description }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="divAvatar">
        {% if person.picture %}
            <img id="avatarImage"  src="{{ person.picture.url }}" alt="{{ person.name }} {{ person.surname }}">
        {% else %}
            <div class="noPicture">
                <i class="fas fa-user-alt"></i>
            </div>
        {% endif %}
    </div>

    <h4 class="h4 h4Colors">Address:</h4>
    {% if address %}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Label</th>
                <th scope="col" class="centerTableCol">Address Data</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Street</td>
                <td>{{ address.street_name }}</td>
            </tr>
            <tr>
                <td>House Number</td>
                <td>{{ address.house_number }}</td>
            </tr>
            <tr>
                <td>Flat Number</td>
                <td>{{ address.flat_number }}</td>
            </tr>
            <tr>
                <td>City</td>
                <td>{{ address.city }}</td>
            </tr>
            </tbody>
        </table>
    {% else %}
        <p>No address defined</p>
    {% endif %}

    <h4 class="h4 h4Colors">Telephone Numbers:</h4>
    {% if phone %}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Telephone Number</th>
                <th scope="col" class="centerTableCol">Type</th>
            </tr>
            </thead>
            <tbody>
            {% for tel_number in phone %}
                <tr>
                    <td class="centerTableCol">{{ tel_number.phone_number }}</td>
                    <td class="centerTableCol">{{ tel_number.get_phone_type_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No email telephone number</p>
    {% endif %}


    <h4 class="h4 h4Colors">Email Addresses:</h4>
    {% if email %}
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="centerTableCol">Email Address</th>
                <th scope="col" class="centerTableCol">Type</th>
            </tr>
            </thead>
            <tbody>
            {% for email_address in email %}
                <tr>
                    <td class="centerTableCol">{{ email_address.email }}</td>
                    <td class="centerTableCol">{{ email_address.get_email_type_display }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No email address</p>
    {% endif %}
    <h4 class="h4 h4Colors">User Groups:</h4>
    {% if person.groups_set.all %}
        <table class="table">
            <tbody>
            {% for gr in person.groups_set.all %}
                <tr>
                    <td>{{ gr.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>User not assigned to any groups</p>
    {% endif %}

    <hr>
    <a href="/modify/{{ person.id }}">
        <button type="submit" class="btn btn-warning">Modify Person!</button>
    </a>
    <a href="/delete_person/{{ person.id }}">
        <button class="btn btn-danger">Delete Person!</button>
    </a>
{% endif %}
{% include "footer.html" %}

contacts_manager/contacts/templates/standard_error_message.html
{% include  "header.html" %}

{% if error_msg %}
    <h3 class="h3">{{ error_msg }}</h3>
    <br>
    <a href="{{ next }}">
        <button class="btn btn-primary">Back</button>
    </a>

{% else %}
    Nothing here .......!!!! Check code!

{% endif %}

{% include "footer.html" %}